#ifndef MAINWINDOW_CONSTANTS_H
#define MAINWINDOW_CONSTANTS_H

#define LNA_MIN 0
#define LNA_MAX 40
#define LNA_STEP 8

#define VGA_MIN 0
#define VGA_MAX 62
#define VGA_STEP 2

const double MIN_SAMPLE_RATE_MHZ = 2.0;
const double MAX_SAMPLE_RATE_MHZ = 20.0;
const double DEFAULT_SAMPLE_RATE_MHZ = 2.0;

const double MIN_BANDWIDTH_MHZ = 1.0;
const double MAX_BANDWIDTH_MHZ = 20.0;
const double DEFAULT_BANDWIDTH_MHZ = 2.0;

const double ANALYSIS_MIN_FREQ_MHZ = 1.0;
const double ANALYSIS_MAX_FREQ_MHZ = 6000.0;
const double ANALYSIS_DEFAULT_FREQ_MHZ = 433.0;
const double ANALYSIS_MIN_SPAN_MHZ = 2.0;
const double ANALYSIS_DEFAULT_SPAN_MHZ = 4.0;
const double ANALYSIS_SWEEP_SEGMENT_MHZ = 5.0;
const int ANALYSIS_MAX_SWEEP_SEGMENTS = 64;
const int ANALYSIS_SWEEP_SETTLE_MS = 12;
const int ANALYSIS_DEFAULT_SWEEP_FFT_SIZE = 1024;
const int ANALYSIS_WATERFALL_MAX_BINS = 4096;
const double ANALYSIS_MIN_SAMPLE_RATE_MHZ = 2.0;
const unsigned ANALYSIS_DEFAULT_LNA_GAIN = 24;
const unsigned ANALYSIS_DEFAULT_VGA_GAIN = 20;

const double DETECTION_MIN_FREQ_MHZ = 400.0;
const double DETECTION_MAX_FREQ_MHZ = 450.0;
const double DETECTION_DEFAULT_FREQ_MHZ = 405.125;
const double DETECTION_DEFAULT_SAMPLE_RATE_MHZ = 4.8;
const double DETECTION_DEFAULT_BANDWIDTH_MHZ = 2.0;
const int DETECTION_DEFAULT_FFT_SIZE = 1024;
const unsigned DETECTION_DEFAULT_LNA_GAIN = 24;
const unsigned DETECTION_DEFAULT_VGA_GAIN = 20;

const int THRESHOLD_STEP = 1;
const int THRESHOLD_MIN = -100;
const int THRESHOLD_MAX = 50;

#endif
